allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                if (namespace != null) {
                    namespace project.namespace
                }
            }
        }
    }
}

subprojects {
    project.plugins.withId("kotlin-android") {
        project.kotlin {
            jvmToolchain(17)
        }
    }
}
